config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  # rails generate controller StaticPages home help
  # created these two routes
  # Note: root and '#' makes the main page when logging on
  # Note: get and '/' makes additional pages
  
  root 'sessions#new'

  
  get 'help' => 'static_pages#help'
  get 'front' => 'users#front'
  get 'back' => 'users#back'
  get 'all' => 'users#all'
 # get 'home' => 'static_pages#home'
  get 'create' => 'users#new'
 # get 'users' => 'users#index'
 # post 'front' => 'sessions#new'

  
  # for logging in
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  
    
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
   
  
  
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :role, presence: true, allow_nil: false
  validates :question_one_new, presence: true, allow_nil: true
  validates :question_two, presence: true, allow_nil: true
  validates :question_three, presence: true, allow_nil: true
  validates :question_four, presence: true, allow_nil: true
  validates :question_five, presence: true, allow_nil: true
 # validates :username, presence: true, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
   # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: []
  before_action :correct_user,   only: []
  before_action :admin_user, only: [:index, :edit, :new, :all]
  before_action :second_tier_user, only: [:front, :back]
  #make a page for all, front, and back (for permissions)
  
  def index
    @users = User.all
  end 

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  # Back of House evaluation form
  def back
    @users = User.order("name").where(:role => 2).page(params[:page]).per(1)
  end
  
  # Front of House evaluation form
  def front
    @users = User.order("name").where(:role => 1).page(params[:page]).per(1)
  end
  
  # All evaluation form (for directors)
  def all
    @users = User.order("name").where.not(:role => 0).page(params[:page]).per(1)
  end
 
  def create
    @user = User.new(user_params)
    if @user.save
      @user.update_attribute :question_one_new, 0.0
      @user.update_attribute :question_two, 0.0
      @user.update_attribute :question_three, 0.0
      @user.update_attribute :question_four, 0.0
      @user.update_attribute :question_five, 0.0
      @user.update_attribute :one_counter, 0
      @user.update_attribute :two_counter, 0
      @user.update_attribute :three_counter, 0
      @user.update_attribute :four_counter, 0
      @user.update_attribute :five_counter, 0
      if @user.role == 0 
         @user.update_attribute :admin, true
      end
      if @user.role == 3 || @user.role == 4 || @user.role == 5
         @user.update_attribute :second_tier, true
      else
        @user.update_attribute :second_tier, false
      end
      #log_in @user
      flash[:success] = "Team Member successfully Created!"
      redirect_to users_url
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end 
  
  
  #question_one_new = final result
  #current_one = current result
  #total_one = all the results
  def update
    @user = User.find(params[:id])
    average = 0
    
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      
      # QUESTION ONE: HUNGER FOR WISDOM
      if @user.current_one == 1 
         @user.increment(:one_counter, 1)
         @user.save
         @user.increment(:total_one, 1)
         average = (@user.total_one / @user.one_counter)
         @user.update_attribute :question_one_new, average
      end
      if @user.current_one == 2
         @user.increment(:one_counter, 1)
         @user.save
         @user.increment(:total_one, 2)
         average = (@user.total_one / @user.one_counter)
         @user.update_attribute :question_one_new, average
      end
      if @user.current_one == 3 
         @user.increment(:one_counter, 1)
         @user.save
         @user.increment(:total_one, 3)
         average = (@user.total_one / @user.one_counter)
         @user.update_attribute :question_one_new, average
      end
      if @user.current_one == 4
         @user.increment(:one_counter, 1)
         @user.save
         @user.increment(:total_one, 4)
         average = (@user.total_one / @user.one_counter)
         @user.update_attribute :question_one_new, average
      end
      if @user.current_one == 5
         @user.increment(:one_counter, 1)
         @user.save
         @user.increment(:total_one, 5)
         average = (@user.total_one / @user.one_counter)
         @user.update_attribute :question_one_new, average
      end
      
      # QUESTION TWO: EXPECT THE BEST
      average1 = 0
      if @user.current_two == 1 
         @user.increment(:two_counter, 1)
         @user.save
         @user.increment(:total_two, 1)
         average1 = (@user.total_two / @user.two_counter)
         @user.update_attribute :question_two, average1
      end
      if @user.current_two == 2
         @user.increment(:two_counter, 1)
         @user.save
         @user.increment(:total_two, 2)
         average1 = (@user.total_two / @user.two_counter)
         @user.update_attribute :question_two, average1
      end
      if @user.current_two == 3 
         @user.increment(:two_counter, 1)
         @user.save
         @user.increment(:total_two, 3)
         average1 = (@user.total_two / @user.two_counter)
         @user.update_attribute :question_two, average1
      end
      if @user.current_two == 4
         @user.increment(:two_counter, 1)
         @user.save
         @user.increment(:total_two, 4)
         average1 = (@user.total_two / @user.two_counter)
         @user.update_attribute :question_two, average1
      end
      if @user.current_two == 5
         @user.increment(:two_counter, 1)
         @user.save
         @user.increment(:total_two, 5)
         average1 = (@user.total_two / @user.two_counter)
         @user.update_attribute :question_two, average1
      end
      
      # QUESTION THREE: ACCEPT RESPONSIBILITY
      average2 = 0
      if @user.current_three == 1 
         @user.increment(:three_counter, 1)
         @user.save
         @user.increment(:total_three, 1)
         average2 = (@user.total_three / @user.three_counter)
         @user.update_attribute :question_three, average2
      end
      if @user.current_three == 2
         @user.increment(:three_counter, 1)
         @user.save
         @user.increment(:total_three, 2)
         average2 = (@user.total_three / @user.three_counter)
         @user.update_attribute :question_three, average2
      end
      if @user.current_three == 3 
         @user.increment(:three_counter, 1)
         @user.save
         @user.increment(:total_three, 3)
         average2 = (@user.total_three / @user.three_counter)
         @user.update_attribute :question_three, average2
      end
      if @user.current_three == 4
         @user.increment(:three_counter, 1)
         @user.save
         @user.increment(:total_three, 4)
         average2 = (@user.total_three / @user.three_counter)
         @user.update_attribute :question_three, average2
      end
      if @user.current_three == 5
         @user.increment(:three_counter, 1)
         @user.save
         @user.increment(:total_three, 5)
         average2 = (@user.total_three / @user.three_counter)
         @user.update_attribute :question_three, average2
      end
      
      # QUESTION FOUR: RESPOND WITH COURAGE
      average3 = 0
      if @user.current_four == 1 
         @user.increment(:four_counter, 1)
         @user.save
         @user.increment(:total_four, 1)
         average3 = (@user.total_four / @user.four_counter)
         @user.update_attribute :question_four, average3
      end
      if @user.current_four == 2
         @user.increment(:four_counter, 1)
         @user.save
         @user.increment(:total_four, 2)
         average3 = (@user.total_four / @user.four_counter)
         @user.update_attribute :question_four, average3
      end
      if @user.current_four == 3 
         @user.increment(:four_counter, 1)
         @user.save
         @user.increment(:total_four, 3)
         average3 = (@user.total_four / @user.four_counter)
         @user.update_attribute :question_four, average3
      end
      if @user.current_four == 4
         @user.increment(:four_counter, 1)
         @user.save
         @user.increment(:total_four, 4)
         average3 = (@user.total_four / @user.four_counter)
         @user.update_attribute :question_four, average3
      end
      if @user.current_four == 5
         @user.increment(:four_counter, 1)
         @user.save
         @user.increment(:total_four, 5)
         average3 = (@user.total_four / @user.four_counter)
         @user.update_attribute :question_four, average3
      end
      
      # QUESTION FIVE: THANK OTHERS FIRST
      average4 = 0
      if @user.current_five == 1 
         @user.increment(:five_counter, 1)
         @user.save
         @user.increment(:total_five, 1)
         average4 = (@user.total_five / @user.five_counter)
         @user.update_attribute :question_five, average4
      end
      if @user.current_five == 2
         @user.increment(:five_counter, 1)
         @user.save
         @user.increment(:total_five, 2)
         average4 = (@user.total_five / @user.five_counter)
         @user.update_attribute :question_five, average4
      end
      if @user.current_five == 3 
         @user.increment(:five_counter, 1)
         @user.save
         @user.increment(:total_five, 3)
         average4 = (@user.total_five / @user.five_counter)
         @user.update_attribute :question_five, average4
      end
      if @user.current_five == 4
         @user.increment(:five_counter, 1)
         @user.save
         @user.increment(:total_five, 4)
         average4 = (@user.total_five / @user.five_counter)
         @user.update_attribute :question_five, average4
      end
      if @user.current_five == 5
         @user.increment(:five_counter, 1)
         @user.save
         @user.increment(:total_five, 5)
         average4 = (@user.total_five / @user.five_counter)
         @user.update_attribute :question_five, average4
         flash[:success] = "Team member's scores were added! Please select 'Next Employee' below to continue"
      end
      
      
      
      # ADD ADMIN AND SECOND_TIER UPDATES HERE
      if @user.role == 0 
         @user.update_attribute :admin, true
      end
      if @user.role == 3 || @user.role == 4 || @user.role == 5
         @user.update_attribute :second_tier, true
         @user.update_attribute :admin, false
      end
      if @user.role == 1 || @user.role == 2
        @user.update_attribute :admin, false
        @user.update_attribute :second_tier, false
      end
      
      #flash[:success] = "Profile updated"
         redirect_to :back
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private
  
  def user_params
      params.require(:user).permit(:name, :email, :password,

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.username)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<!-- THINK ABOUT HAVING ADMIN COLUMN AGAIN FOR PERMISSION PURPOSES -->

<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/all.html.erb
<h2>Back of House Evaluation</h2>
<br> </br>

<% @users.each do |user| %>
    
    <h4> <%= user.name  %> </h4>
    <h3> Do you have HEART?</h3>
    
    
    <%= form_for(user) do |f| %>
    <% begin %>
        
        
           <div class="form-group">
            <%= f.label :Hunger_for_wisdom %></label
            <div class="col-xs-10">
            <div class="form-inline">
            <div class="form-group">
                 <%= f.radio_button :current_one, 1 %>
                 <%= f.label :_1 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_one, 2 %>
                 <%= f.label :_2 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_one, 3 %>
                 <%= f.label :_3 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_one, 4 %>
                 <%= f.label :_4 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_one, 5 %>
                 <%= f.label :_5 %>
            </div>
        </div>
    </div>
    
    <div class="form-group">
            <%= f.label :Expect_the_Best %></label
            <div class="col-xs-10">
            <div class="form-inline">
            <div class="form-group">
                 <%= f.radio_button :current_two, 1 %>
                 <%= f.label :_1 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_two, 2 %>
                 <%= f.label :_2 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_two, 3 %>
                 <%= f.label :_3 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_two, 4 %>
                 <%= f.label :_4 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_two, 5 %>
                 <%= f.label :_5 %>
            </div>
        </div>
    </div>
    
     <div class="form-group">
            <%= f.label :Accept_Responsibility %></label
            <div class="col-xs-10">
            <div class="form-inline">
            <div class="form-group">
                 <%= f.radio_button :current_three, 1 %>
                 <%= f.label :_1 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_three, 2 %>
                 <%= f.label :_2 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_three, 3 %>
                 <%= f.label :_3 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_three, 4 %>
                 <%= f.label :_4 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_three, 5 %>
                 <%= f.label :_5 %>
            </div>
        </div>
    </div>
    
    
    <div class="form-group">
            <%= f.label :Respond_with_Courage %></label
            <div class="col-xs-10">
            <div class="form-inline">
            <div class="form-group">
                 <%= f.radio_button :current_four, 1 %>
                 <%= f.label :_1 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_four, 2 %>
                 <%= f.label :_2 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_four, 3 %>
                 <%= f.label :_3 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_four, 4 %>
                 <%= f.label :_4 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_four, 5 %>
                 <%= f.label :_5 %>
            </div>
        </div>
    </div>
    
     <div class="form-group">
            <%= f.label :Thank_others_first %></label
            <div class="col-xs-10">
            <div class="form-inline">
            <div class="form-group">
                 <%= f.radio_button :current_five, 1 %>
                 <%= f.label :_1 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_five, 2 %>
                 <%= f.label :_2 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_five, 3 %>
                 <%= f.label :_3 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_five, 4 %>
                 <%= f.label :_4 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_five, 5 %>
                 <%= f.label :_5 %>
            </div>
        </div>
    </div>
        
         <div class="col-md-3 col-md-offset-4">
      <%= f.submit "Submit Score", class: "btn btn-default" %>
      


        <% rescue ActionController::RedirectBackError %>
        
        
</div>
</div>
   
    <% end %>
    
    <%= paginate @users %>
   
   <% end %>
   
<% end %>

app/views/users/back.html.erb
<h2>Back of House Evaluation</h2>
<br> </br>

<% @users.each do |user| %>
    
    <h4> <%= user.name  %> </h4>
    <h3> Do you have HEART?</h3>
    
    
    <%= form_for(user) do |f| %>
    <% begin %>
        
        
           <div class="form-group">
            <%= f.label :Hunger_for_wisdom %></label
            <div class="col-xs-10">
            <div class="form-inline">
            <div class="form-group">
                 <%= f.radio_button :current_one, 1 %>
                 <%= f.label :_1 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_one, 2 %>
                 <%= f.label :_2 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_one, 3 %>
                 <%= f.label :_3 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_one, 4 %>
                 <%= f.label :_4 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_one, 5 %>
                 <%= f.label :_5 %>
            </div>
        </div>
    </div>
    
    <div class="form-group">
            <%= f.label :Expect_the_Best %></label
            <div class="col-xs-10">
            <div class="form-inline">
            <div class="form-group">
                 <%= f.radio_button :current_two, 1 %>
                 <%= f.label :_1 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_two, 2 %>
                 <%= f.label :_2 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_two, 3 %>
                 <%= f.label :_3 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_two, 4 %>
                 <%= f.label :_4 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_two, 5 %>
                 <%= f.label :_5 %>
            </div>
        </div>
    </div>
    
     <div class="form-group">
            <%= f.label :Accept_Responsibility %></label
            <div class="col-xs-10">
            <div class="form-inline">
            <div class="form-group">
                 <%= f.radio_button :current_three, 1 %>
                 <%= f.label :_1 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_three, 2 %>
                 <%= f.label :_2 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_three, 3 %>
                 <%= f.label :_3 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_three, 4 %>
                 <%= f.label :_4 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_three, 5 %>
                 <%= f.label :_5 %>
            </div>
        </div>
    </div>
    
    
    <div class="form-group">
            <%= f.label :Respond_with_Courage %></label
            <div class="col-xs-10">
            <div class="form-inline">
            <div class="form-group">
                 <%= f.radio_button :current_four, 1 %>
                 <%= f.label :_1 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_four, 2 %>
                 <%= f.label :_2 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_four, 3 %>
                 <%= f.label :_3 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_four, 4 %>
                 <%= f.label :_4 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_four, 5 %>
                 <%= f.label :_5 %>
            </div>
        </div>
    </div>
    
     <div class="form-group">
            <%= f.label :Thank_others_first %></label
            <div class="col-xs-10">
            <div class="form-inline">
            <div class="form-group">
                 <%= f.radio_button :current_five, 1 %>
                 <%= f.label :_1 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_five, 2 %>
                 <%= f.label :_2 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_five, 3 %>
                 <%= f.label :_3 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_five, 4 %>
                 <%= f.label :_4 %>
            </div>
            <div class="form-group">
                 <%= f.radio_button :current_five, 5 %>
                 <%= f.label :_5 %>
            </div>
        </div>
    </div>
        
         <div class="col-md-3 col-md-offset-4">
      <%= f.submit "Submit Score", class: "btn btn-default" %>
      


        <% rescue ActionController::RedirectBackError %>
        
        
</div>
</div>
   
    <% end %>
    
    <%= paginate @users %>
   
   <% end %>
   
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h2>Update Your Profile</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :Role %> 
      <%= f.select :role, options_for_select([["Director", 0], ["Manager", 3],
          ["Front of House Shift Leader", 4], ["Back of House Shift Leader", 5],
          ["Front of House Team Member", 1], ["Back of House Team Member", 2]]),
          :prompt => 'Select One' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

  <div class="col-md-4 col-md-offset-4">
      <%= f.submit "Save changes", class: "btn btn-default" %>
      </div>
    <% end %>

   
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All employees') %>
<h2>All Employees</h2>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      <%= link_to "Edit", edit_user_path(user) %>
      <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "Delete", user, method: :delete,
                                  data: { confirm: "Are you sure you would like to delete this employee?" } %>
  <% end %>
      <% if user.role == 0 %>
          <p>Director</p>
        <% end %>
        <% if user.role == 1 %>
          <p>Front of House Team Member</p>
        <% end %>
        <% if user.role == 2 %>
          <p>Back of House Team Member</p>
        <% end %>
        <% if user.role == 3 %>
          <p>Manager</p>
        <% end %>
        <% if user.role == 4 %>
          <p>Front of House Shift Leader</p>
        <% end %>
        <% if user.role == 5 %>
          <p>Back of House Shift Leader</p>
        <% end %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<!-- sign up page. Will need to add front/back
of house and only allow directors to use this-->


<% provide(:title, 'Create New Team Member') %>
<h2>Create New Team Member</h2>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control', :placeholder =>"" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
     
      <%= f.label :Role %> 
      <%= f.select :role, options_for_select([["Director", 0], ["Manager", 3],
          ["Front of House Shift Leader", 4], ["Back of House Shift Leader", 5],
          ["Front of House Team Member", 1], ["Back of House Team Member", 2]]),
          :prompt => 'Select One' %>
         
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

  <div class="col-md-6 col-md-offset-3">
      <%= f.submit "Create my account", class: "btn btn-default" %>
  </div>
      
    <% end %>
    
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h4>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h4>
      <h5>
        <% if @user.role == 0 %>
          <h3>Director</h3>
        <% end %>
        <% if @user.role == 1 %>
          <h3>Front of House</h3>
          <h3>Team Member</h3>
        <% end %>
        <% if @user.role == 2 %>
          <h3>Back of House</h3>
          <h3>Team Member</h3>
        <% end %>
         <% if @user.role == 3 %>
          <h3>Manager</h3>
        <% end %>
         <% if @user.role == 4 %>
          <h3>Front of House</h3>
          <h3>Shift Leader</h3>
        <% end %>
         <% if @user.role == 5 %>
          <h3>Back of House</h3>
          <h3>Shift Leader</h3>
        <% end %>
      </h5>
      
      <h2> <%= @user.question_one_new %> </h2>
      <h2> <%= @user.question_two %> </h2>
      <h2> <%= @user.question_three%> </h2>
      <h2> <%= @user.question_four%> </h2>
      <h2> <%= @user.question_five%> </h2>
      
      <div class="col-md-3 col-md-offset-4">
      <% if @user.role == 3 || @user.role == 0 %>
       <%= link_to "Evaluate Team Members", all_path, class: "btn btn-lg btn-default" %>
      <% end %>
      
      <% if @user.role == 4 %>
       <%= link_to "Evaluate Front of House", front_path, class: "btn btn-lg btn-default" %>
      <% end %>
      
      <% if @user.role == 5 %>
       <%= link_to "Evaluate Back of House", back_path, class: "btn btn-lg btn-default" %>
      <% end %>
      </div>
    </section>
  </aside>
</div>