config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  # rails generate controller StaticPages home help
  # created these two routes
  # Note: root and '#' makes the main page when logging on
  # Note: get and '/' makes additional pages
  
  root 'sessions#new'

  
  get 'help' => 'static_pages#help'
  get 'front' => 'users#front'
  get 'back' => 'users#back'
  get 'all' => 'users#all'
 # get 'home' => 'static_pages#home'
  get 'create' => 'users#new'
 # get 'users' => 'users#index'
 # post 'front' => 'sessions#new'

  
  # for logging in
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  
    
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <small>
    <a>Chick-fil-A 38th and Steele</a>
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <% if logged_in? %>
      <%= link_to "Chick-Fil-A", current_user, id: "logo" %>
    <% end %>
    <% if !logged_in? %>
      <%= link_to "Chick-Fil-A", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Home", current_user %></li>
          
        <% end %>
        <% if !logged_in? %>
          <li><%= link_to "Home", root_path %></li>
        <% end %>
        <% if logged_in? %>
        <% if @current_user.role == 0 %>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Employees <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View all Users", users_path %></li>
              <li><%= link_to "Add New User", create_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% end %>
          <% if @current_user.role == 1 || @current_user.role == 2 || @current_user.role == 3 || @current_user.role == 4 || @current_user.role == 5 %>
           <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% end %>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!-- This is automatically generage with every Rails file
 I'm assuming that this is additional homepage stuff alongside
 the 'root' in routes -->

<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
   
    <%= render 'layouts/header' %>
     
    <div class="container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>